teleop_gui:
  ros__parameters:
    default_robot_ip: 192.168.1.211
    default_reverse_ip: 192.168.1.10
    ur_type: ur5
    default_input_type: joy
    default_gripper_type: robotiq
    default_joy_profile: xbox
    joy_profiles:
    - auto
    - xbox
    - ps5
    - generic
    default_mediapipe_input_topic: /d455/camera/color/image_raw
    default_mediapipe_camera: d455
    default_mediapipe_camera_serial_number: '146222254305'
    mediapipe_camera_options:
    - d435
    - d455
    - oakd
    - camera
    realsense_d435_serial_number: ''
    realsense_d455_serial_number: ''
    default_collector_global_camera_model: d455
    default_collector_global_camera_serial_number: '146222254305'
    default_collector_wrist_camera_model: d435
    default_collector_wrist_camera_serial_number: '231522070265'
    default_inference_global_camera_source: realsense
    default_inference_global_camera_model: d455
    default_inference_global_camera_serial_number: '146222254305'
    default_inference_wrist_camera_source: realsense
    default_inference_wrist_camera_model: d455
    default_inference_wrist_camera_serial_number: '146222254305'
    default_inference_model_dir: /home/rvl/collect_datasets_ws/models/10-07-25
    default_inference_env: fruits
    default_inference_task: pick_up_the_starfruit_and_place_it_in_the_basket
    default_inference_embedding_path: /home/rvl/collect_datasets_ws/Real_IL/task_embeddings/data_fruits.pkl
    default_inference_device: cuda
    default_inference_hz: 20.0
    default_inference_action_timeout_sec: 0.25
    collect_inference_action_logs: false
    camera_driver_options:
    - realsense
    - oakd
    default_camera_driver: realsense
    default_global_camera_source: realsense
    default_wrist_camera_source: realsense
    realsense_enable_depth: false
    oakd_enable_depth: false
    default_hdf5_output_dir: /home/rvl/collect_datasets_ws/data505
    default_hdf5_filename: wk2.hdf5
    default_inference_backend: openpi_remote
    default_openpi_host: 127.0.0.1
    default_openpi_port: 18000
    default_openpi_prompt: put the apple into the blue box
